name: render potyarkin.ml

on:
  push:
    branches:
      - smallweb

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
      - uses: actions/cache@v3
        with:
          path: cache/webring
          key: webring-${{ hashFiles('content/blogroll.yml') }}
      - run: make publish
        env:
          PIP_CACHE_DIR: cache/pip
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
          publish_branch: html
          commit_message: |-
            render: ${{ github.event.head_commit.message }}

            Render static website for GitHub pages from
            commit
